### ISSUE TITLE
User Story: additional product images

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#1]
As a a shopper  I can see various images of the product so that get as much information for my shopping decision as possible

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I can see all available images related to the product 
2: I can click on any of the images to enlarge the image
3:

------------------------

## Tasks

- [ ]  Task1: Create ProductImage model
- [ ] Task 2: load all images for a given product into the product_detail page 
- [ ] Task 3: display the first image large and the rest as thumbnails next to the bigger image
- [ ] Task 4: write js code on click on a thumbnail to set it as the bigger image
