### ISSUE TITLE
User Story: edit/add bottler, cask type, brand etc. for products

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#14]
As a store owner I can edit/add bottler, cask type etc. for products so that all relevant information to help shoppers to buy the right product are stored for my products
------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I can add/edit bottler, cask type, category, product size, product type, product brand to new or existing products
2:
3:

------------------------

## Tasks

- [ ] Task 1: add necessary buttons to add_product/edit_product page to allow adding a new entry if necessary (e.g. new brand) for each of the models directly  
- [ ] Task 2: add necessary logic in add_product/edit_product view
- [ ] Task 3: test functionality
