### ISSUE TITLE
User Story: manage taste categories for new/existing products

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#15]
As a store owner I can add/remove taste categories to my products so that I have all product up to date with relevant information 

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I can select all relevant taste categories for a product when adding or editing a product
2: I can remove taste categories not relevant when editing a product
3:

------------------------

## Tasks

- [ ] Task 1: add necessary elements to add_product/edit_product page
- [ ] Task 2: add code to handle add/remove taste category in add_product and edit_product view
- [ ] Task 3: test functionality
