### ISSUE TITLE
User Story: fix mobile view of bag

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#19]
As a shopper I can see the bag page on my mobile screen so that I can shop conveniently on my mobile

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I can see a well designed the bag page on my mobile
2: I can increase or decrease the quantity on my mobile
3: I can remove the product from the bag

------------------------

## Tasks

- [ ] Task 1: turn table into bootstrap grid
- [ ] Task 2: adjust grid to show well on mobile and desktop
- [ ] Task 3: ensure js code works in all orientations
