### ISSUE TITLE
User Story: show taste categories for products

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#2]
As a shopper I can see all taste categories  so that can imagine what the whiskey might taste like and can make  sure the whiskey I buy is to my taste

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I see all taste categories associated with the selected whiskey in the product detail view
2:
3:

------------------------

## Tasks

- [ ] Task 1 : create a a TasteCategory model to capture standard taste categories
- [ ] Task 2:  create a model (ProductTasteCategory) to capture the taste categories of whiskey in the shop inventory
- [ ] Task 3:  retrieve the entries in the ProductTasteCategory and relevant info from TasteCategory and make it available in the product detail view
- [ ] Task 4: display the taste categories for the selected product in the products_detail page
