### ISSUE TITLE
User Story: search by taste category

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#3]
As a shopper I can search products by desired taste categories so that I can select whiskeys I like
------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I can click on search and select any taste category I like from a list
2: I get all whiskeys in inventory that matched my taste category selection
3:

------------------------

## Tasks

- [ ] Task 1: modify the search bar to present a list of all taste categories from the TasteCategory model
- [ ] Task 2: all the shopper to select and deselect all taste categories he/she wants
- [ ] Task 3: display the selected taste categories in the search bar and/or on page incl. option to add or remove tastes 
- [ ] Task 4: search for all products that match the selection of taste categories 
- [ ] Task 5: display only products in the products page that match the search criteria
