### ISSUE TITLE
User Story: enforce age restriction on entering the site

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#4]
As a (European) store owner I validate that shopper entering the site are older then 18 so that adhere to legal requirements  

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: a shopper has to enter his birthday and is only allowed to proceed to the site when older than 18 
2:
3:

------------------------

## Tasks

- [ ] Task 1: add modal form on home with prompt to enter shoppers birthday
- [ ] Task 2: calculate if shopper is older than 18
- [ ] Task 3: if shopper is older than 18 allow shopper to see and shop products otherwise decline entrance
- [ ] Task 4: optional: store birthday for later use in user profile
