### ISSUE TITLE
User Story: show featured product in home view

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#5]
As a store owner I can select a product to show on home as FEATURED product so that I can push sales for this product

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I can set a product to 'featured' and the featured product is displayed on the home page
2: 
3:

------------------------

## Tasks

- [ ] Task 1: add featured as BooleanField to my products model
- [ ] Task 2: add field/test in my add and update product pages
- [ ] Task 3: add featured product to home.html
