### ISSUE TITLE
User Story: style product_details page according to wireframes

### ISSUE THREAD

**Issue by troeske** [troeske/holyspirits#9]
As a shopper I can see all relevant Information on the product_detailsscreen on mobile and larger devices so that I have a convenient shopping experience and easily find the whiskey(s) I want to buy 

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: the  product_details screen looks great on mobile and larger devices
2:
3:

------------------------

## Tasks

- [ ] Task 1: review wireframes for mobile screens and implement respective changes
- [ ] Task 2: review wireframes for larger screens and implement respective changes
- [ ] Task 3: test implementation on various screen sizes
